### ISSUE TITLE
cnpm安装的scrappeteer 报错.

### ISSUE THREAD

**Issue by Ipanyiwen** [chfw/echarts-scrappeteer#2]
/usr/local/node/bin/scrappeteer https://pyecharts.github.io/echarts-china-cities-js/preview.html
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/node/lib/node_modules/echarts-scrappeteer/node_modules/_puppeteer@0.13.0@puppeteer/.local-chromium/linux-515411/chrome-linux/chrome EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by chfw** [comment]
node.js 的权限管理问题，建议搜一下 `node.js EACCES`。或者不用系统的node.js， 而是用用户自己node.js.

**Comment by CGerAJ** [comment]
```
npm install --unsafe-perm node_modules_name
```
